* Encoding: UTF-8.
* Encoding: UTF-8


### Nach Patienten filtern, die eine Stim-Off Testung haben:
    
USE ALL.
COMPUTE filter_$=(Datum_Testung_Stim_OFF > 0).
VARIABLE LABELS filter_$ 'Datum_Testung_Stim_OFF > 0 (FILTER)'.
VALUE LABELS filter_$ 0 'Not Selected' 1 'Selected'.
FORMATS filter_$ (f1.0).
FILTER BY filter_$.
EXECUTE.


### Deskriptive Statistik
    
FREQUENCIES VARIABLES=Geschlecht Dominanztyp BDI_12MFU SAS_12MFU QUIP_12MFU DemTect_12MFU 
    MMST_12MFU ADL_12MFU UPDRS_I_12MFU UPDRS_II_12MFU UPDRS_III_stimON_medOFF_12MFU 
    UPDRS_III_stimON_medON_12MFU UPDRS_III_stimOFF_medOFF_12MFU UPDRS_III_stimOFF_medON_12MFU 
    UPDRS_IV_12MFU MOCA_12MFU CKI_12MFU MNA_SF_12MFU LEDD_12MFU Alter_bei_Testung Erkrankungsdauer ROPAD    
  /STATISTICS=STDDEV MINIMUM MAXIMUM MEAN MEDIAN
  /ORDER=ANALYSIS.

FREQUENCIES VARIABLES=MOTML_12MFU RTISMDRT_12MFU RTIFMDRT_12MFU PRMPCI_12MFU SSPFSL_12MFU 
    SSPRSL_12MFU ERTTH_12MFU PRMPCD_12MFU VRMFRDS_12MFU VRMIRTC_12MFU MTTTIC_12MFU MTTLMD_12MFU 
    MTTICMD_12MFU MTTMTCMD_12MFU SWMBE468_12MFU SWMS_12MFU PALTEA_12MFU PALFAMS_12MFU VRMDRTC_12MFU 
    MOTML_12MFU_STIM_OFF RTISMDRT_12MFU_STIM_OFF RTIFMDRT_12MFU_STIM_OFF PRMPCI_12MFU_STIM_OFF 
    SSPFSL_12MFU_STIM_OFF SSPRSL_12MFU_STIM_OFF ERTTH_12MFU_STIM_OFF PRMPCD_12MFU_STIM_OFF 
    VRMFRDS_12MFU_STIM_OFF VRMIRTC_12MFU_STIM_OFF MTTTIC_12MFU_STIM_OFF MTTLMD_12MFU_STIM_OFF 
    MTTICMD_12MFU_STIM_OFF MTTMTCMD_12MFU_STIM_OFF SWMBE468_12MFU_STIM_OFF SWMS_12MFU_STIM_OFF 
    PALTEA_12MFU_STIM_OFF PALFAMS_12MFU_STIM_OFF VRMDRTC_12MFU_STIM_OFF
  /NTILES=4
  /STATISTICS=STDDEV MEAN MEDIAN
  /ORDER=ANALYSIS.


### Wilcoxon signed-rank tests StimON vs. StimON, jeweils Paarbildung mit deskriptiver Statistik

NPAR TESTS
  /WILCOXON=MOTML_12MFU RTISMDRT_12MFU RTIFMDRT_12MFU RTISMDMT_12MFU RTIFMDMT_12MFU PRMPCI_12MFU SSPFSL_12MFU SSPRSL_12MFU 
    ERTTH_12MFU PRMPCD_12MFU VRMFRDS_12MFU VRMIRTC_12MFU MTTTIC_12MFU MTTLMD_12MFU MTTICMD_12MFU 
    MTTMTCMD_12MFU SWMBE468_12MFU SWMS_12MFU PALTEA_12MFU PALFAMS_12MFU VRMDRTC_12MFU WITH 
    MOTML_12MFU_STIM_OFF RTISMDRT_12MFU_STIM_OFF RTIFMDRT_12MFU_STIM_OFF RTISMDMT_12MFU_STIM_OFF RTIFMDMT_12MFU_STIM_OFF PRMPCI_12MFU_STIM_OFF 
    SSPFSL_12MFU_STIM_OFF SSPRSL_12MFU_STIM_OFF ERTTH_12MFU_STIM_OFF PRMPCD_12MFU_STIM_OFF 
    VRMFRDS_12MFU_STIM_OFF VRMIRTC_12MFU_STIM_OFF MTTTIC_12MFU_STIM_OFF MTTLMD_12MFU_STIM_OFF 
    MTTICMD_12MFU_STIM_OFF MTTMTCMD_12MFU_STIM_OFF SWMBE468_12MFU_STIM_OFF SWMS_12MFU_STIM_OFF 
    PALTEA_12MFU_STIM_OFF PALFAMS_12MFU_STIM_OFF VRMDRTC_12MFU_STIM_OFF (PAIRED)
  /STATISTICS DESCRIPTIVES 
  /MISSING ANALYSIS.

###  Additional median change and 95% CI

NPTESTS
  /RELATED TEST(MOTML_12MFU MOTML_12MFU_STIM_OFF) WILCOXON HODGES_LEHMAN
  /CRITERIA ALPHA=0.05 CILEVEL=95
  /MISSING SCOPE=ANALYSIS USERMISSING=EXCLUDE.

NPTESTS
  /RELATED TEST(RTISMDRT_12MFU RTISMDRT_12MFU_STIM_OFF) WILCOXON HODGES_LEHMAN
  /CRITERIA ALPHA=0.05 CILEVEL=95
  /MISSING SCOPE=ANALYSIS USERMISSING=EXCLUDE.

NPTESTS
  /RELATED TEST(RTIFMDRT_12MFU RTIFMDRT_12MFU_STIM_OFF) WILCOXON HODGES_LEHMAN
  /CRITERIA ALPHA=0.05 CILEVEL=95
  /MISSING SCOPE=ANALYSIS USERMISSING=EXCLUDE.

NPTESTS
  /RELATED TEST(RTISMDMT_12MFU RTISMDMT_12MFU_STIM_OFF) WILCOXON HODGES_LEHMAN
  /CRITERIA ALPHA=0.05 CILEVEL=95
  /MISSING SCOPE=ANALYSIS USERMISSING=EXCLUDE.

NPTESTS
  /RELATED TEST(RTIFMDMT_12MFU RTIFMDMT_12MFU_STIM_OFF) WILCOXON HODGES_LEHMAN
  /CRITERIA ALPHA=0.05 CILEVEL=95
  /MISSING SCOPE=ANALYSIS USERMISSING=EXCLUDE.

NPTESTS
  /RELATED TEST(PRMPCI_12MFU PRMPCI_12MFU_STIM_OFF) WILCOXON HODGES_LEHMAN
  /CRITERIA ALPHA=0.05 CILEVEL=95
  /MISSING SCOPE=ANALYSIS USERMISSING=EXCLUDE.

NPTESTS
  /RELATED TEST(SSPFSL_12MFU SSPFSL_12MFU_STIM_OFF) WILCOXON HODGES_LEHMAN
  /CRITERIA ALPHA=0.05 CILEVEL=95
  /MISSING SCOPE=ANALYSIS USERMISSING=EXCLUDE.

NPTESTS
  /RELATED TEST(SSPRSL_12MFU SSPRSL_12MFU_STIM_OFF) WILCOXON HODGES_LEHMAN
  /CRITERIA ALPHA=0.05 CILEVEL=95
  /MISSING SCOPE=ANALYSIS USERMISSING=EXCLUDE.

NPTESTS
  /RELATED TEST(ERTTH_12MFU ERTTH_12MFU_STIM_OFF) WILCOXON HODGES_LEHMAN
  /CRITERIA ALPHA=0.05 CILEVEL=95
  /MISSING SCOPE=ANALYSIS USERMISSING=EXCLUDE.

NPTESTS
  /RELATED TEST(PRMPCD_12MFU PRMPCD_12MFU_STIM_OFF) WILCOXON HODGES_LEHMAN
  /CRITERIA ALPHA=0.05 CILEVEL=95
  /MISSING SCOPE=ANALYSIS USERMISSING=EXCLUDE.

NPTESTS
  /RELATED TEST(VRMFRDS_12MFU VRMFRDS_12MFU_STIM_OFF) WILCOXON HODGES_LEHMAN
  /CRITERIA ALPHA=0.05 CILEVEL=95
  /MISSING SCOPE=ANALYSIS USERMISSING=EXCLUDE.

NPTESTS
  /RELATED TEST(VRMIRTC_12MFU VRMIRTC_12MFU_STIM_OFF) WILCOXON HODGES_LEHMAN
  /CRITERIA ALPHA=0.05 CILEVEL=95
  /MISSING SCOPE=ANALYSIS USERMISSING=EXCLUDE.

NPTESTS
  /RELATED TEST(MTTTIC_12MFU MTTTIC_12MFU_STIM_OFF) WILCOXON HODGES_LEHMAN
  /CRITERIA ALPHA=0.05 CILEVEL=95
  /MISSING SCOPE=ANALYSIS USERMISSING=EXCLUDE.

NPTESTS
  /RELATED TEST(MTTLMD_12MFU MTTLMD_12MFU_STIM_OFF) WILCOXON HODGES_LEHMAN
  /CRITERIA ALPHA=0.05 CILEVEL=95
  /MISSING SCOPE=ANALYSIS USERMISSING=EXCLUDE.

NPTESTS
  /RELATED TEST(MTTICMD_12MFU MTTICMD_12MFU_STIM_OFF) WILCOXON HODGES_LEHMAN
  /CRITERIA ALPHA=0.05 CILEVEL=95
  /MISSING SCOPE=ANALYSIS USERMISSING=EXCLUDE.

NPTESTS
  /RELATED TEST(MTTMTCMD_12MFU MTTMTCMD_12MFU_STIM_OFF) WILCOXON HODGES_LEHMAN
  /CRITERIA ALPHA=0.05 CILEVEL=95
  /MISSING SCOPE=ANALYSIS USERMISSING=EXCLUDE.

NPTESTS
  /RELATED TEST(SWMBE468_12MFU SWMBE468_12MFU_STIM_OFF) WILCOXON HODGES_LEHMAN
  /CRITERIA ALPHA=0.05 CILEVEL=95
  /MISSING SCOPE=ANALYSIS USERMISSING=EXCLUDE.

NPTESTS
  /RELATED TEST(SWMS_12MFU SWMS_12MFU_STIM_OFF) WILCOXON HODGES_LEHMAN
  /CRITERIA ALPHA=0.05 CILEVEL=95
  /MISSING SCOPE=ANALYSIS USERMISSING=EXCLUDE.

NPTESTS
  /RELATED TEST(PALTEA_12MFU PALTEA_12MFU_STIM_OFF) WILCOXON HODGES_LEHMAN
  /CRITERIA ALPHA=0.05 CILEVEL=95
  /MISSING SCOPE=ANALYSIS USERMISSING=EXCLUDE.

NPTESTS
  /RELATED TEST(PALFAMS_12MFU PALFAMS_12MFU_STIM_OFF) WILCOXON HODGES_LEHMAN
  /CRITERIA ALPHA=0.05 CILEVEL=95
  /MISSING SCOPE=ANALYSIS USERMISSING=EXCLUDE.

NPTESTS
  /RELATED TEST(VRMDRTC_12MFU VRMDRTC_12MFU_STIM_OFF) WILCOXON HODGES_LEHMAN
  /CRITERIA ALPHA=0.05 CILEVEL=95
  /MISSING SCOPE=ANALYSIS USERMISSING=EXCLUDE.





### Spearman correlations between relative StimON versus StimOFF differences of the MDS-UPDRS III or mean reaction time in the MOT and CANTAB relative StimONOFF-Differences
    
NONPAR CORR
  /VARIABLES=UPDRSIII_relDiff_OffOn tremor_relDiff_OffOn rigidity_relDiff_OffOn bradykinesia_relDiff_OffOn MOTML_relDiff_OffOn RTISMDRT_relDiff_OffOn 
    RTIFMDRT_relDiff_OffOn RTISMDMT_relDiff_OffOn RTIFMDMT_relDiff_OffOn MTTLMD_relDiff_OffOn
  /PRINT=SPEARMAN TWOTAIL NOSIG FULL
  /MISSING=PAIRWISE.


